# Generated by Django 3.1.7 on 2021-02-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/TEMP/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('skusize', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('colournum', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=60)),
                ('buyprice', models.FloatField(default=0.0)),
                ('sellprice', models.FloatField(default=0.0)),
                ('buycurrency', models.CharField(max_length=20)),
                ('costpriceowncurrency', models.FloatField(default=0.0)),
                ('costcurrency', models.CharField(max_length=20)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('collection', models.CharField(max_length=200)),
                ('brandname', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=20)),
                ('sizerange', models.CharField(max_length=20)),
                ('article', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('skusize', models.CharField(max_length=25)),
                ('colour', models.CharField(max_length=50)),
                ('buyprice', models.FloatField(default=0.0)),
                ('style', models.CharField(max_length=25)),
                ('colournum', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(default=0)),
                ('barcode', models.ForeignKey(db_column='barcode', on_delete=django.db.models.deletion.CASCADE, to='stockapp.product', to_field='barcode')),
            ],
        ),
    ]
